### ISSUE TITLE
fb2cal fails to authenticate

### ISSUE THREAD

**Issue by adilsond** [mobeigi/fb2cal#121]
Hi.

Since this month fb2cal fails to authenticate. Maybe it is caused by a change in the endpoint.

And the password is correct since I can still authenticate from a regular browser.

**Comment by mobeigi** [comment]
Hi @adilsond ,

First of all, thanks for the bug report and also for including a `DEBUG` log!
I've gone ahead and removed your log file after looking at so it doesn't leak anything that might be sensitive like cookies etc.

The issue here is that Facebook changed their authentication rules.
We've been sending the password using `pass` in plaintext (but over HTTPS so still secure) so far. 
Facebook no longer allows this (which means it completely breaks Facebook for people using no Javascript browsers!).

Instead, Facebook is now enforcing we pass a `enc_pass` encrypted version of the password which they first started using around 2019 but it wasn't enforced like it is now.

Thankfully, other people like @lorenzodifuccia have already done the hard work to generate this encrypted password.
https://gist.github.com/lorenzodifuccia/c857afa47ede66db852e6a25c0a1a027

Fix is ready and tested on my end, pushing changes now!

**Comment by mobeigi** [comment]
@adilsond Did it manage to work for you? Let me know.

**Comment by adilsond** [comment]
> @adilsond Did it manage to work for you? Let me know.

It is working here.  Thanks.
