### ISSUE TITLE
Incomplete composer query response for get_entity_id_from_vanity_name

### ISSUE THREAD

**Issue by dvmcconnell** [mobeigi/fb2cal#18]
In `get_entity_id_from_vanity_name` I was frequently getting an empty list back in `json_response['payload']['entries']`, so I inspected the json and noticed the `lid` key. I tried using that when there weren't any `'entries'`, and everything worked like magic - something like:

```
    if not json_response['payload']['entries']:
        return json_response['lid']
```

Not sure if anyone else is having this issue, but thought I would post anyway.

Thanks so much for creating this!

**Comment by mobeigi** [comment]
I've had the `COMPOSER_QUERY_ENDPOINT` fail on me before where it would kind of be rate limited after being hit too quickly. More info in my writeup: http://bit.ly/fb2cal-blogpost

However, this seems like a **different** issue.
I'm not too sure why the `json_response['payload']['entries']` would be empty. Could you dump the entire `json_response` to file and post it here or email me the payload at [me@mobeigi.com](mailto:me@mobeigi.com). The composer query endpoint should have no sensitive data besides your friends name (`value` query param).

In either case, falling back to use the `json_response['lid']` shouldn't be an issue.

**Comment by dvmcconnell** [comment]
sure here you go
```
{
  "lid": "6719972747743822150", 
  "__ar": 1, 
  "gkxData": {}, 
  "bootloadable": {}, 
  "qexData": {}, 
  "bxData": {}, 
  "ixData": {}, 
  "payload": {
    "end_of_threads": true, 
    "entries": []
  }
}
```

**Comment by mobeigi** [comment]
@dvmcconnell That isn't right at all. That `lid` key seems to be related to something entirely different. What has happened here is that an entity id failed to be fetched and your code changes just made it use some arbitrary id instead of causing the script to fail. This will result in duplicate entries in your calendar every time its imported if the calendar UID is not unique for one of your friends.

Issue #2 will help in this scenario. Also the aforementioned limitation of the `COMPOSER_QUERY_ENDPOINT` is probably what you are facing too. I suggest removing your change and running the original version again, it should work for you after some time. If not more logging via #12 is coming soon.

**Comment by dvmcconnell** [comment]
Ah alright, thanks for the info
