### ISSUE TITLE
Why is it recommended to run the script every 24 hours?

### ISSUE THREAD

**Issue by 8549** [mobeigi/fb2cal#39]
Birthdays don't change that often, so why is it recommended in the documentation, in bold, to run the script every 24 hours?

**Comment by mobeigi** [comment]
Hey, if you observed the original Facebook ics file you'd see the `X-PUBLISHED-TTL:PT12H` header suggesting that the calendar application should poll for updates every 12 hours. I originally had the recommended cron job time as 12 hours but doubled it to 24 hours.

Ultimately, every 24 hours may be too frequent for most users. Personally I like it running daily in the odd chance that I add someone who's birthday is upcoming. Otherwise, once a week or even month should work just as well for most.

Do you think its worth updating the docu so its clearler?

**Comment by Taegost** [comment]
I think another important point to make on running it daily is also in case anybody in your Friends List changes their privacy settings to change how their birthday is shown (or not show it at all), then they'll be removed from the calendar appropriately.

**Comment by mobeigi** [comment]
@Taegost That is another good point! I didn't even consider that, good catch. 👍

**Comment by 8549** [comment]
@mobeigi Yes, I think that would be something worth mentioning in the documentation.
About @Taegost's point, I think that kinda subverts the whole point of this script, but that would also be what Facebook would do with their "official" calendar.
