### ISSUE TITLE
Grab year of birth

### ISSUE THREAD

**Issue by cbncbncnbvb** [mobeigi/fb2cal#40]
Hey, first of all thank you for your script. It would be nice to have the year of birth as well (if provided by user). 

I myself would love a CSV output like 
userid,username,birthdate,year_of_birth rather than a ics file which outdates the next year, but thats just me.

**Comment by mobeigi** [comment]
The year of birth is unfortunately not provided in the AJAX response we parse. We could fetch the year of birth from a users profile separely which would add `len(friends_with_bdays)` extra get requests. Probably need to find a more effecient way of doing this if possible.

Just FYI, the current behaviour does mimic the original Facebook feature (which did not provide year of birth). Furthermore, the ICS file won't become out of date the following year, each Birthday event repeats yearly.

Also this issue should probably be two issues, one for a CSV output feature and the other for including the birthday year.

**Comment by cbncbncnbvb** [comment]
Thank you for your quick reply. 

I had a look into the code and the response in the meantime. I do not yet understand why the script is rather slow, but for yearth of birth I think the way to go is to call https://www.facebook.com/{uid}/about?section=contact_basic for every freind (well, for those friends, that do provide birthdays at all.

The code is quite easy to understand (thanks for that) and I consider modifying it myself. if you are interested, I would provide the updated code back to you.

**Comment by hybrid2102** [comment]
> The code is quite easy to understand (thanks for that) and I consider modifying it myself. if you are interested, I would provide the updated code back to you.

Please, share! I'd like to have the year as well.

**Comment by mobeigi** [comment]
@cbncbncnbvb @hybrid2102 

We can add this in as extra functionality. An extra 2 minutes processing time won't hurt too much I suppose given that most people seem to run this script once.

**Comment by VladimirBelov** [comment]
Any update for birth year support inside fb2cal?

**Comment by mobeigi** [comment]
> Any update for birth year support inside fb2cal?

Not yet. The same issue exists where fetching the birth year from the users profile would incur a huge performance hit. The script would take many many minutes to run vs only taking a few seconds.

We need to find another endpoint that exposes this in bulk but it may not exist.
Keep in mind the old Birthday export feature did not support this either (there was no Birthday year, only day and month).

**Comment by VladimirBelov** [comment]
https://www.facebook.com/{username}/about_contact_and_basic_info

**Comment by mobeigi** [comment]
Update: I looked into this and sadly we don't have the information we need.

Facebook uses a REST relay for their public GraphQL endpoint.
It uses stored queries with a `doc_id` field. This means we don't have control over what data to query for.

The endpoint right now returns a data set that looks like this:
![image](https://user-images.githubusercontent.com/5266113/98916451-4c584800-251f-11eb-9b9a-3f4a627695e7.png)

The recent and upcoming data shows a few recent/upcoming birthdays and these are the ones that have the birthday year.
Unfortunately, we need Birthdays for all friends which we can get from **viewer** -> **all_friends_by_birthday_month** but these only contain the birthday day and month. The good news is we also now get the users Facebook **id** (we couldn't before)!

However, making this change is still good because it makes the script much better (because we don't need to deal with locales and languages or any complex calculations). So the change was made here: #81 

The ideal solution now I think is adding an optional config setting to also fetch Birthday years manually, one for each Facebook friend. This will be very slow depending on how we do it but at least it will work for those who run this script rarely.

**Comment by mobeigi** [comment]
Good news, a new GraphQL endpoint has been added by Facebook which is identical to the old one but includes the birthday year for all your friends!

You can run `v1.2.4` of the script to now include the Birthday year.

![chrome_l5vneJqVLI](https://user-images.githubusercontent.com/5266113/170195238-1c1cb442-a97a-4b8e-9ca2-2fe0dcb595d8.png)

And this is what it looks like if user has their birth year hidden/private.
![chrome_lcOo1Khrae](https://user-images.githubusercontent.com/5266113/170195243-70d44acb-002d-4d7e-b545-7ff24d9233bb.png)

PR here: https://github.com/mobeigi/fb2cal/pull/108

CC: @cbncbncnbvb , @hybrid2102 , @VladimirBelov , @bonelifer
