### ISSUE TITLE
AttributeError: 'Calendar' object has no attribute '_unused'

### ISSUE THREAD

**Issue by sukrutonline** [mobeigi/fb2cal#44]
After successfully processing (All months):
 get the following error:

Traceback (most recent call last):
  File "SRC./fb2cal.py", line 813, in <module>
  File "SRC./fb2cal.py", line 126, in main
  File "SRC./fb2cal.py", line 782, in populate_birthdays_calendar
AttributeError: 'Calendar' object has no attribute '_unused'

No ICS file is created. (Tried creating both local files as well as google drive)

Not sure whats going on! Can someone help?

**Comment by calvinle** [comment]
Hey @sukrutonline,
After looking into it, ._unused it a function in ics-v0.4. You're likely using v0.6.
(For context, I was running this in Ubuntu bash with Windows Subsystem for Linux). I uninstalled the 0.6 module and replaced it with the 0.4 by running
`pip3 uninstall ics`
`pip3 uninstall ics==0.4`
Program executed successfully after that.

**Comment by mobeigi** [comment]
The `._unused` approach was used to add custom iCal properties to the ICS file since that was the only supported way to do so using the `ics` module.

It looks like it has been renamed in `v0.6`:
https://github.com/C4ptainCrunch/ics.py/commit/79bd4974c6a17b8907c69a306effe906d7607ab2

Docs:
https://icspy.readthedocs.io/en/stable/advanced.html#custom-properties

I think the best approach is to rename the field in fb2cal and update `requirements.txt` to require `v0.6+` (currently it required `v0.4+`).

@calvinle Care to take out a PR for this? 😄

**Comment by sukrutonline** [comment]
Hey @calvinle & @mobeigi,

Thanks for the response!,
After installing v0.4 with your suggestion, It works flawlessly!

pip3 uninstall ics
pip3 install ics==0.4 

Thanks!
